import type { Metadata } from "next";
import { absoluteUrl, site } from "./site";

export type PageSeo = {
  /** Rendered verbatim as <title>. Keep to 50–60 characters. */
  title: string;
  /** Rendered as the meta description and reused for OG/Twitter. Keep to 140–160. */
  description: string;
  /** Site-relative path, leading slash, no trailing slash. Becomes the canonical. */
  path: string;
  /** Utility pages that should resolve but never rank. */
  noIndex?: boolean;
};

/*
 * The routes generated by app/opengraph-image.tsx and app/twitter-image.tsx.
 *
 * These have to be named explicitly. Next applies a file-convention image to a
 * segment and its children only while the child leaves `openGraph` alone — the
 * moment a nested page exports its own `openGraph` block, as every page here
 * does, the inherited image is dropped. Verified by crawling: without this,
 * og:image appeared on "/" and nowhere else.
 */
const OG_IMAGE = "/opengraph-image";
const TWITTER_IMAGE = "/twitter-image";
const OG_IMAGE_ALT = `${site.name} — outsourcing, customer support, and digital growth`;

/**
 * Builds the full metadata block for a page: canonical, Open Graph, and
 * Twitter card, all derived from one title/description pair so the three can't
 * drift apart.
 */
export function buildMetadata({ title, description, path, noIndex }: PageSeo): Metadata {
  const url = absoluteUrl(path);

  return {
    /* absolute, so the "%s | Valentisys" template in the root layout does not
       append a second brand to a title that already ends in one */
    title: { absolute: title },
    description,
    alternates: { canonical: url },
    openGraph: {
      type: "website",
      siteName: site.name,
      locale: site.locale,
      url,
      title,
      description,
      /* metadataBase in the root layout makes these absolute */
      images: [{ url: OG_IMAGE, width: 1200, height: 630, alt: OG_IMAGE_ALT }],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [{ url: TWITTER_IMAGE, width: 1200, height: 630, alt: OG_IMAGE_ALT }],
    },
    ...(noIndex && {
      robots: { index: false, follow: true, googleBot: { index: false, follow: true } },
    }),
  };
}
